### ISSUE TITLE
Issue with H1P whmcs-partner modul

### ISSUE THREAD

**Issue by atiqch** [host1plus/whmcs-partner#1]
I am getting this error message when cron job is running on my WHMCS instance . 

<p class="debug">TypeError: Argument 1 passed to GuzzleHttp\Ring\Client\StreamHandler::__invoke() must be of the type array, object given, called in WHMCS/modules/servers/h1pcloud/vendor/guzzlehttp/guzzle/src/Client.php on line 277 and defined in WHMCS/vendor/guzzlehttp/ringphp/src/Client/StreamHandler.php:26<br />
Stack trace:<br />
#0 WHMCS/modules/servers/h1pcloud/vendor/guzzlehttp/guzzle/src/Client.php(277): GuzzleHttp\Ring\Client\StreamHandler->__invoke(Object(GuzzleHttp\Psr7\Request), Array)<br />
#1 WHMCS/modules/servers/h1pcloud/vendor/guzzlehttp/guzzle/src/Client.php(125): GuzzleHttp\Client->transfer(Object(GuzzleHttp\Psr7\Request), Array)<br />
#2 WHMCS/modules/servers/h1pcloud/vendor/guzzlehttp/guzzle/src/Client.php(131): GuzzleHttp\Client->requestAsync('get', Object(GuzzleHttp\Psr7\Uri), Array)<br />
#3 WHMCS/modules/servers/h1pcloud/vendor/guzzlehttp/guzzle/src/Client.php(89): GuzzleHttp\Client->request('get', 'https://pki.whm...', Array)<br />
#4 WHMCS/vendor/whmcs/whmcs-foundation/lib/Installer/Composer/CertificateManager.php(0): GuzzleHttp\Client->__call('get', Array)<br />
#5 WHMCS/vendor/whmcs/whmcs-foundation/lib/Installer/Composer/CertificateManager.php(0): WHMCS\Installer\Composer\CertificateManager->getUrl('https://pki.whm...')<br />
#6 WHMCS/vendor/whmcs/whmcs-foundation/lib/Installer/Composer/CertificateManager.php(0): WHMCS\Installer\Composer\CertificateManager->getPathFromKeyserver('certs.json')<br              />

**Comment by EdgarasSk** [comment]
Hello.

Could you please answer the following questions:

* Which cron job are you executing?
* Is there more output in the cron? Could you post it?
* What is your PHP version
* Do you have any other 3rd party modules that use composer and install guzzle in base WHMCS vendor?

Seems that error is originating within WHMCS/vendor which none of the modules should be using, so I would need additional output if I am to trace the problem.

Thanks.

**Comment by atiqch** [comment]
Please find answers below:
- ../whmcs/crons/cron.php all
- Yes I can provide log, see response below I received from WHMCS:
- PHP 7.2
- I believe no, I started to face issue after I tried to install H1PCloud module

**Below is response from WHMCS** 
Looking over the log provided, I've determined from the following error that a custom module called "h1pcloud" is trying to load it's own copy of the Guzzle PHP library and is causing this failure as it conflicts with the copy we ship and use throughout WHMCS:

TypeError: Argument 1 passed to GuzzleHttp\Ring\Client\StreamHandler::__invoke() must be of the type array, object given, called in ../whmcs/modules/servers/h1pcloud/vendor/guzzlehttp/guzzle/src/Client.php on line 277 and defined in ../whmcs/vendor/guzzlehttp/ringphp/src/Client/StreamHandler.php:26

Please have the developer of this module fix it to use our included copy of Guzzle instead of trying to pull in a separate copy (which isn't supported) and it should resolve this.

**Comment by atiqch** [comment]
Is there any update ?

**Comment by EdgarasSk** [comment]
Unfortunately module currently does not support PHP 7.2. We've registered this issue but I do not have an ETA on when we might update the module.

Could you please contact our support team over https://www.host1plus.com/ so that they could find a more immediate solution to your problem?

**Comment by cosilva1609** [comment]
We are trying to install the WHMCS module from Host1plu, but from what I saw in the installation manual there are not three required files:

modules
addons
h1papi
servers
h1pcloud
h1pvps

Or is there another way to install it?

**Comment by EdgarasSk** [comment]
Hello @cosilva1609 

I believe I have answered your question in #2
